spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo

  history-level: full
  history-level-default: full
  eventing:
    execution: true
    history: true
    task: true